# Site settings
name: LuckyCat's Blog
email: 17710167359@163.com
author: LuckyCat
url: https://www.luckycathome.com
resume_site: http://www.hifreud.com/Resume.io/
github: https://github.com/LuckyCat7848/
baseurl: ""
description: Everything is well !
meta_description: 康志华;个人博客;学而不思则罔;思而不学则殆;生命不止;折腾不休
motto: Everything is well !
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
gems: [jekyll-paginate]
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: LuckyCat7848
highlighter: rouge

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  toc_levels: 1..6
  extensions:
    - autolink
    - footnotes
    - smart
    - with_toc_data
    - fenced_code_blocks
    - hard_wrap
    - tables
    - strikethrough
    - superscript
    - highlight
    - prettify
    - no_intra_emphasis
  enable_coderay: true
  syntax_highlighter: rouge
  

FB:
  comments :
    provider : duoshuo
    duoshuo:
        short_name : LCat78480 
    disqus :
        short_name : LuckyCat 
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light